#!/usr/bin/env python3
"""Tek seferlik: i18n/qr_lang_patches.json üretir (watermark dil kodları)."""
from __future__ import annotations

import json
from pathlib import Path

# Avrupa / Asya çevirileri — eksik anahtar kalmaması için her dil tam küme.
KEYS = [
    "qr.input.placeholder",
    "qr.settings.type",
    "qr.settings.resolution",
    "qr.settings.colors",
    "qr.settings.fgColor",
    "qr.settings.bgColor",
    "qr.settings.showBg",
    "qr.settings.cornerRadius",
    "qr.settings.customSize",
    "qr.settings.sizeUnit",
    "qr.download",
    "qr.type.website",
    "qr.type.wifi",
    "qr.type.vcard",
    "qr.type.email",
    "qr.type.phone",
    "qr.wifi.ssid",
    "qr.wifi.password",
    "qr.wifi.hidden",
    "qr.wifi.noEncryption",
    "qr.wifi.enc.wpa",
    "qr.wifi.enc.wep",
    "qr.vcard.firstName",
    "qr.vcard.lastName",
    "qr.vcard.phone",
    "qr.vcard.email",
    "qr.vcard.company",
    "qr.vcard.jobTitle",
    "qr.vcard.address",
    "qr.vcard.website",
    "qr.email.address",
    "qr.email.subject",
    "qr.email.body",
    "qr.phone.number",
]


def row(*vals: str) -> dict[str, str]:
    return dict(zip(KEYS, vals))


PATCHES: dict[str, dict[str, str]] = {
    "fi": row(
        "Kirjoita URL tai teksti tähän...",
        "QR-tyyppi",
        "Resoluutio",
        "Värit",
        "Etualan väri",
        "Taustaväri",
        "Näytä tausta",
        "Kulmien säde",
        "Mukautettu koko (px)",
        "px",
        "Lataa QR-koodi",
        "Verkkosivusto",
        "Wi-Fi",
        "Yhteystieto (vCard)",
        "Sähköposti",
        "Puhelin",
        "Verkon nimi (SSID)",
        "Salasana",
        "Piilotettu verkko",
        "Ei salausta",
        "WPA/WPA2",
        "WEP",
        "Etunimi",
        "Sukunimi",
        "Puhelinnumero",
        "Sähköposti",
        "Yritys",
        "Titteli",
        "Osoite",
        "Verkkosivusto",
        "Sähköpostiosoite",
        "Aihe",
        "Viesti",
        "Puhelinnumero",
    ),
    "de": row(
        "URL oder Text hier eingeben...",
        "QR-Typ",
        "Auflösung",
        "Farben",
        "Vordergrundfarbe",
        "Hintergrundfarbe",
        "Hintergrund anzeigen",
        "Eckenradius",
        "Benutzerdefinierte Größe (px)",
        "px",
        "QR-Code herunterladen",
        "Website",
        "WLAN",
        "Kontakt (vCard)",
        "E-Mail",
        "Telefon",
        "Netzwerkname (SSID)",
        "Passwort",
        "Verstecktes Netzwerk",
        "Keine",
        "WPA/WPA2",
        "WEP",
        "Vorname",
        "Nachname",
        "Telefon",
        "E-Mail",
        "Firma",
        "Berufsbezeichnung",
        "Adresse",
        "Website",
        "E-Mail-Adresse",
        "Betreff",
        "Nachricht",
        "Telefonnummer",
    ),
    "fr": row(
        "Saisissez l’URL ou le texte ici...",
        "Type de QR",
        "Résolution",
        "Couleurs",
        "Couleur d’avant-plan",
        "Couleur d’arrière-plan",
        "Afficher l’arrière-plan",
        "Rayon des coins",
        "Taille personnalisée (px)",
        "px",
        "Télécharger le code QR",
        "Site web",
        "Wi-Fi",
        "Contact (vCard)",
        "E-mail",
        "Téléphone",
        "Nom du réseau (SSID)",
        "Mot de passe",
        "Réseau masqué",
        "Aucun",
        "WPA/WPA2",
        "WEP",
        "Prénom",
        "Nom",
        "Téléphone",
        "E-mail",
        "Entreprise",
        "Intitulé du poste",
        "Adresse",
        "Site web",
        "Adresse e-mail",
        "Objet",
        "Message",
        "Numéro de téléphone",
    ),
    "es": row(
        "Introduce la URL o el texto aquí...",
        "Tipo de QR",
        "Resolución",
        "Colores",
        "Color de primer plano",
        "Color de fondo",
        "Mostrar fondo",
        "Radio de esquinas",
        "Tamaño personalizado (px)",
        "px",
        "Descargar código QR",
        "Sitio web",
        "Wi-Fi",
        "Contacto (vCard)",
        "Correo",
        "Teléfono",
        "Nombre de red (SSID)",
        "Contraseña",
        "Red oculta",
        "Ninguno",
        "WPA/WPA2",
        "WEP",
        "Nombre",
        "Apellidos",
        "Teléfono",
        "Correo electrónico",
        "Empresa",
        "Puesto",
        "Dirección",
        "Sitio web",
        "Dirección de correo",
        "Asunto",
        "Mensaje",
        "Número de teléfono",
    ),
    "it": row(
        "Inserisci URL o testo qui...",
        "Tipo QR",
        "Risoluzione",
        "Colori",
        "Colore in primo piano",
        "Colore di sfondo",
        "Mostra sfondo",
        "Raggio angoli",
        "Dimensione personalizzata (px)",
        "px",
        "Scarica codice QR",
        "Sito web",
        "Wi-Fi",
        "Contatto (vCard)",
        "Email",
        "Telefono",
        "Nome rete (SSID)",
        "Password",
        "Rete nascosta",
        "Nessuna",
        "WPA/WPA2",
        "WEP",
        "Nome",
        "Cognome",
        "Telefono",
        "Email",
        "Azienda",
        "Qualifica",
        "Indirizzo",
        "Sito web",
        "Indirizzo email",
        "Oggetto",
        "Messaggio",
        "Numero di telefono",
    ),
    "nl": row(
        "Voer hier URL of tekst in...",
        "QR-type",
        "Resolutie",
        "Kleuren",
        "Voorgrondkleur",
        "Achtergrondkleur",
        "Achtergrond tonen",
        "Hoekradius",
        "Aangepaste grootte (px)",
        "px",
        "QR-code downloaden",
        "Website",
        "Wi-Fi",
        "Contact (vCard)",
        "E-mail",
        "Telefoon",
        "Netwerknaam (SSID)",
        "Wachtwoord",
        "Verborgen netwerk",
        "Geen",
        "WPA/WPA2",
        "WEP",
        "Voornaam",
        "Achternaam",
        "Telefoon",
        "E-mail",
        "Bedrijf",
        "Functietitel",
        "Adres",
        "Website",
        "E-mailadres",
        "Onderwerp",
        "Bericht",
        "Telefoonnummer",
    ),
    "pl": row(
        "Wpisz tutaj adres URL lub tekst...",
        "Typ kodu QR",
        "Rozdzielczość",
        "Kolory",
        "Kolor pierwszego planu",
        "Kolor tła",
        "Pokaż tło",
        "Promień narożników",
        "Niestandardowy rozmiar (px)",
        "px",
        "Pobierz kod QR",
        "Strona internetowa",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-mail",
        "Telefon",
        "Nazwa sieci (SSID)",
        "Hasło",
        "Sieć ukryta",
        "Brak",
        "WPA/WPA2",
        "WEP",
        "Imię",
        "Nazwisko",
        "Telefon",
        "E-mail",
        "Firma",
        "Stanowisko",
        "Adres",
        "Strona internetowa",
        "Adres e-mail",
        "Temat",
        "Treść wiadomości",
        "Numer telefonu",
    ),
    "pt": row(
        "Introduza o URL ou o texto aqui...",
        "Tipo de QR",
        "Resolução",
        "Cores",
        "Cor de primeiro plano",
        "Cor de fundo",
        "Mostrar fundo",
        "Raio dos cantos",
        "Tamanho personalizado (px)",
        "px",
        "Descarregar código QR",
        "Website",
        "Wi-Fi",
        "Contacto (vCard)",
        "E-mail",
        "Telefone",
        "Nome da rede (SSID)",
        "Palavra-passe",
        "Rede oculta",
        "Nenhum",
        "WPA/WPA2",
        "WEP",
        "Nome próprio",
        "Apelido",
        "Telefone",
        "E-mail",
        "Empresa",
        "Cargo",
        "Morada",
        "Website",
        "Endereço de e-mail",
        "Assunto",
        "Mensagem",
        "Número de telefone",
    ),
    "ru": row(
        "Введите URL или текст...",
        "Тип QR",
        "Разрешение",
        "Цвета",
        "Цвет переднего плана",
        "Цвет фона",
        "Показывать фон",
        "Радиус углов",
        "Свой размер (px)",
        "px",
        "Скачать QR-код",
        "Веб-сайт",
        "Wi-Fi",
        "Контакт (vCard)",
        "Эл. почта",
        "Телефон",
        "Имя сети (SSID)",
        "Пароль",
        "Скрытая сеть",
        "Нет",
        "WPA/WPA2",
        "WEP",
        "Имя",
        "Фамилия",
        "Телефон",
        "Эл. почта",
        "Компания",
        "Должность",
        "Адрес",
        "Веб-сайт",
        "Адрес эл. почты",
        "Тема",
        "Сообщение",
        "Номер телефона",
    ),
    "uk": row(
        "Введіть URL або текст...",
        "Тип QR",
        "Роздільна здатність",
        "Кольори",
        "Колір переднього плану",
        "Колір тла",
        "Показувати тло",
        "Радіус кутів",
        "Власний розмір (px)",
        "px",
        "Завантажити QR-код",
        "Вебсайт",
        "Wi-Fi",
        "Контакт (vCard)",
        "Електронна пошта",
        "Телефон",
        "Назва мережі (SSID)",
        "Пароль",
        "Прихована мережа",
        "Немає",
        "WPA/WPA2",
        "WEP",
        "Ім’я",
        "Прізвище",
        "Телефон",
        "Електронна пошта",
        "Компанія",
        "Посада",
        "Адреса",
        "Вебсайт",
        "Адреса електронної пошти",
        "Тема",
        "Повідомлення",
        "Номер телефону",
    ),
    "cs": row(
        "Zadejte URL nebo text...",
        "Typ QR",
        "Rozlišení",
        "Barvy",
        "Barva popředí",
        "Barva pozadí",
        "Zobrazit pozadí",
        "Zaoblení rohů",
        "Vlastní velikost (px)",
        "px",
        "Stáhnout QR kód",
        "Webová stránka",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-mail",
        "Telefon",
        "Název sítě (SSID)",
        "Heslo",
        "Skrytá síť",
        "Žádné",
        "WPA/WPA2",
        "WEP",
        "Jméno",
        "Příjmení",
        "Telefon",
        "E-mail",
        "Společnost",
        "Pracovní pozice",
        "Adresa",
        "Webová stránka",
        "E-mailová adresa",
        "Předmět",
        "Zpráva",
        "Telefonní číslo",
    ),
    "sk": row(
        "Zadajte URL alebo text...",
        "Typ QR",
        "Rozlíšenie",
        "Farby",
        "Farba popredia",
        "Farba pozadia",
        "Zobraziť pozadie",
        "Zaoblenie rohov",
        "Vlastná veľkosť (px)",
        "px",
        "Stiahnuť QR kód",
        "Webová stránka",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-mail",
        "Telefón",
        "Názov siete (SSID)",
        "Heslo",
        "Skrytá sieť",
        "Žiadne",
        "WPA/WPA2",
        "WEP",
        "Meno",
        "Priezvisko",
        "Telefón",
        "E-mail",
        "Spoločnosť",
        "Pracovná pozícia",
        "Adresa",
        "Webová stránka",
        "E-mailová adresa",
        "Predmet",
        "Správa",
        "Telefónne číslo",
    ),
    "sv": row(
        "Ange URL eller text här...",
        "QR-typ",
        "Upplösning",
        "Färger",
        "Förgrundsfärg",
        "Bakgrundsfärg",
        "Visa bakgrund",
        "Hörnradie",
        "Anpassad storlek (px)",
        "px",
        "Ladda ner QR-kod",
        "Webbplats",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-post",
        "Telefon",
        "Nätverksnamn (SSID)",
        "Lösenord",
        "Dolt nätverk",
        "Ingen",
        "WPA/WPA2",
        "WEP",
        "Förnamn",
        "Efternamn",
        "Telefon",
        "E-post",
        "Företag",
        "Befattning",
        "Adress",
        "Webbplats",
        "E-postadress",
        "Ämne",
        "Meddelande",
        "Telefonnummer",
    ),
    "da": row(
        "Indtast URL eller tekst her...",
        "QR-type",
        "Opløsning",
        "Farver",
        "Forgrundsfarve",
        "Baggrundsfarve",
        "Vis baggrund",
        "Hjørneradius",
        "Brugerdefineret størrelse (px)",
        "px",
        "Download QR-kode",
        "Website",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-mail",
        "Telefon",
        "Netværksnavn (SSID)",
        "Adgangskode",
        "Skjult netværk",
        "Ingen",
        "WPA/WPA2",
        "WEP",
        "Fornavn",
        "Efternavn",
        "Telefon",
        "E-mail",
        "Virksomhed",
        "Stilling",
        "Adresse",
        "Website",
        "E-mailadresse",
        "Emne",
        "Besked",
        "Telefonnummer",
    ),
    "no": row(
        "Skriv inn URL eller tekst her...",
        "QR-type",
        "Oppløsning",
        "Farger",
        "Forgrunnsfarge",
        "Bakgrunnsfarge",
        "Vis bakgrunn",
        "Hjørneradius",
        "Tilpasset størrelse (px)",
        "px",
        "Last ned QR-kode",
        "Nettsted",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-post",
        "Telefon",
        "Nettverksnavn (SSID)",
        "Passord",
        "Skjult nettverk",
        "Ingen",
        "WPA/WPA2",
        "WEP",
        "Fornavn",
        "Etternavn",
        "Telefon",
        "E-post",
        "Bedrift",
        "Stilling",
        "Adresse",
        "Nettsted",
        "E-postadresse",
        "Emne",
        "Melding",
        "Telefonnummer",
    ),
    "is": row(
        "Sláðu inn vefslóð eða texta hér...",
        "QR-tegund",
        "Upplausn",
        "Litir",
        "Litur í forgrunni",
        "Bakgrunnslitur",
        "Sýna bakgrunn",
        "Radíus horna",
        "Sérsniðin stærð (px)",
        "px",
        "Sækja QR-kóða",
        "Vefsíða",
        "Wi-Fi",
        "Tengiliður (vCard)",
        "Tölvupóstur",
        "Sími",
        "Heiti nets (SSID)",
        "Lykilorð",
        "Falið net",
        "Ekkert",
        "WPA/WPA2",
        "WEP",
        "Fornafn",
        "Eftirnafn",
        "Sími",
        "Tölvupóstur",
        "Fyrirtæki",
        "Starfsheiti",
        "Heimilisfang",
        "Vefsíða",
        "Netfang",
        "Efni",
        "Skilaboð",
        "Símanúmer",
    ),
    "hu": row(
        "Írja be az URL-t vagy a szöveget...",
        "QR típus",
        "Felbontás",
        "Színek",
        "Előtérszín",
        "Háttérszín",
        "Háttér megjelenítése",
        "Sarok sugara",
        "Egyéni méret (px)",
        "px",
        "QR-kód letöltése",
        "Weboldal",
        "Wi-Fi",
        "Névjegy (vCard)",
        "E-mail",
        "Telefon",
        "Hálózat neve (SSID)",
        "Jelszó",
        "Rejtett hálózat",
        "Nincs",
        "WPA/WPA2",
        "WEP",
        "Keresztnév",
        "Vezetéknév",
        "Telefon",
        "E-mail",
        "Cég",
        "Beosztás",
        "Cím",
        "Weboldal",
        "E-mail-cím",
        "Tárgy",
        "Üzenet",
        "Telefonszám",
    ),
    "ro": row(
        "Introduceți URL-ul sau textul aici...",
        "Tip QR",
        "Rezoluție",
        "Culori",
        "Culoare prim-plan",
        "Culoare fundal",
        "Afișează fundalul",
        "Raza colțurilor",
        "Dimensiune personalizată (px)",
        "px",
        "Descarcă codul QR",
        "Site web",
        "Wi-Fi",
        "Contact (vCard)",
        "E-mail",
        "Telefon",
        "Nume rețea (SSID)",
        "Parolă",
        "Rețea ascunsă",
        "Fără",
        "WPA/WPA2",
        "WEP",
        "Prenume",
        "Nume",
        "Telefon",
        "E-mail",
        "Companie",
        "Funcție",
        "Adresă",
        "Site web",
        "Adresă de e-mail",
        "Subiect",
        "Mesaj",
        "Număr de telefon",
    ),
    "bg": row(
        "Въведете URL или текст тук...",
        "Тип QR",
        "Резолюция",
        "Цветове",
        "Цвят на преден план",
        "Цвят на фона",
        "Показване на фона",
        "Радиус на ъглите",
        "Персонализиран размер (px)",
        "px",
        "Изтегляне на QR код",
        "Уебсайт",
        "Wi-Fi",
        "Контакт (vCard)",
        "Имейл",
        "Телефон",
        "Име на мрежата (SSID)",
        "Парола",
        "Скрита мрежа",
        "Няма",
        "WPA/WPA2",
        "WEP",
        "Име",
        "Фамилия",
        "Телефон",
        "Имейл",
        "Компания",
        "Длъжност",
        "Адрес",
        "Уебсайт",
        "Имейл адрес",
        "Тема",
        "Съобщение",
        "Телефонен номер",
    ),
    "hr": row(
        "Unesite URL ili tekst ovdje...",
        "Tip QR-a",
        "Rezolucija",
        "Boje",
        "Boja prednjeg plana",
        "Boja pozadine",
        "Prikaži pozadinu",
        "Radijus kutova",
        "Prilagođena veličina (px)",
        "px",
        "Preuzmi QR kod",
        "Web stranica",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-pošta",
        "Telefon",
        "Naziv mreže (SSID)",
        "Lozinka",
        "Skrivena mreža",
        "Nema",
        "WPA/WPA2",
        "WEP",
        "Ime",
        "Prezime",
        "Telefon",
        "E-pošta",
        "Tvrtka",
        "Radno mjesto",
        "Adresa",
        "Web stranica",
        "Adresa e-pošte",
        "Predmet",
        "Poruka",
        "Broj telefona",
    ),
    "sr": row(
        "Унесите URL или текст овде...",
        "Тип QR-а",
        "Резолуција",
        "Боје",
        "Боја предњег плана",
        "Боја позадине",
        "Прикажи позадину",
        "Радијус углова",
        "Прилагођена величина (px)",
        "px",
        "Преузми QR кôд",
        "Веб-сајт",
        "Wi-Fi",
        "Контакт (vCard)",
        "Имејл",
        "Телефон",
        "Име мреже (SSID)",
        "Лозинка",
        "Скривена мрежа",
        "Нема",
        "WPA/WPA2",
        "WEP",
        "Име",
        "Презиме",
        "Телефон",
        "Имејл",
        "Компанија",
        "Радно место",
        "Адреса",
        "Веб-сајт",
        "Имејл адреса",
        "Наслов",
        "Порука",
        "Број телефона",
    ),
    "bs": row(
        "Unesite URL ili tekst ovdje...",
        "Tip QR koda",
        "Rezolucija",
        "Boje",
        "Boja prednjeg plana",
        "Boja pozadine",
        "Prikaži pozadinu",
        "Radijus uglova",
        "Prilagođena veličina (px)",
        "px",
        "Preuzmi QR kod",
        "Web stranica",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-pošta",
        "Telefon",
        "Naziv mreže (SSID)",
        "Lozinka",
        "Skrivena mreža",
        "Nema",
        "WPA/WPA2",
        "WEP",
        "Ime",
        "Prezime",
        "Telefon",
        "E-pošta",
        "Kompanija",
        "Radno mjesto",
        "Adresa",
        "Web stranica",
        "Adresa e-pošte",
        "Predmet",
        "Poruka",
        "Broj telefona",
    ),
    "sl": row(
        "Vnesite URL ali besedilo tukaj...",
        "Vrsta QR",
        "Ločljivost",
        "Barve",
        "Barva ospredja",
        "Barva ozadja",
        "Prikaži ozadje",
        "Radij vogalov",
        "Velikost po meri (px)",
        "px",
        "Prenesi QR kodo",
        "Spletna stran",
        "Wi-Fi",
        "Stik (vCard)",
        "E-pošta",
        "Telefon",
        "Ime omrežja (SSID)",
        "Geslo",
        "Skrito omrežje",
        "Brez",
        "WPA/WPA2",
        "WEP",
        "Ime",
        "Priimek",
        "Telefon",
        "E-pošta",
        "Podjetje",
        "Delovno mesto",
        "Naslov",
        "Spletna stran",
        "E-poštni naslov",
        "Zadeva",
        "Sporočilo",
        "Telefonska številka",
    ),
    "sq": row(
        "Shkruani URL ose tekst këtu...",
        "Lloji i QR",
        "Rezolucioni",
        "Ngjyrat",
        "Ngjyra e parplanit",
        "Ngjyra e sfondit",
        "Shfaq sfondin",
        "Rrezja e qosheve",
        "Madhësia e personalizuar (px)",
        "px",
        "Shkarko kodin QR",
        "Faqja e internetit",
        "Wi-Fi",
        "Kontakt (vCard)",
        "Email",
        "Telefon",
        "Emri i rrjetit (SSID)",
        "Fjalëkalimi",
        "Rrjet i fshehur",
        "Asnjë",
        "WPA/WPA2",
        "WEP",
        "Emri",
        "Mbiemri",
        "Telefon",
        "Email",
        "Kompania",
        "Titulli i punës",
        "Adresa",
        "Faqja e internetit",
        "Adresa e emailit",
        "Subjekti",
        "Mesazhi",
        "Numri i telefonit",
    ),
    "et": row(
        "Sisestage URL või tekst siia...",
        "QR tüüp",
        "Eraldusvõime",
        "Värvid",
        "Esaplaani värv",
        "Tausta värv",
        "Kuva taust",
        "Nurga raadius",
        "Kohandatud suurus (px)",
        "px",
        "Laadi QR-kood alla",
        "Veebileht",
        "Wi-Fi",
        "Kontakt (vCard)",
        "E-post",
        "Telefon",
        "Võrgu nimi (SSID)",
        "Parool",
        "Peidetud võrk",
        "Puudub",
        "WPA/WPA2",
        "WEP",
        "Eesnimi",
        "Perekonnanimi",
        "Telefon",
        "E-post",
        "Ettevõte",
        "Ametinimetus",
        "Aadress",
        "Veebileht",
        "E-posti aadress",
        "Teema",
        "Sõnum",
        "Telefoninumber",
    ),
    "lt": row(
        "Įveskite URL arba tekstą čia...",
        "QR tipas",
        "Raiška",
        "Spalvos",
        "Priekinio plano spalva",
        "Fono spalva",
        "Rodyti foną",
        "Kampų spindulys",
        "Tinkintas dydis (px)",
        "px",
        "Atsisiųsti QR kodą",
        "Interneto svetainė",
        "Wi-Fi",
        "Kontaktas (vCard)",
        "El. paštas",
        "Telefonas",
        "Tinklo pavadinimas (SSID)",
        "Slaptažodis",
        "Paslėptas tinklas",
        "Nėra",
        "WPA/WPA2",
        "WEP",
        "Vardas",
        "Pavardė",
        "Telefonas",
        "El. paštas",
        "Įmonė",
        "Pareigos",
        "Adresas",
        "Interneto svetainė",
        "El. pašto adresas",
        "Tema",
        "Žinutė",
        "Telefono numeris",
    ),
    "lv": row(
        "Ievadiet URL vai tekstu šeit...",
        "QR tips",
        "Izšķirtspēja",
        "Krāsas",
        "Priekšplāna krāsa",
        "Fona krāsa",
        "Rādīt fonu",
        "Stūru rādiuss",
        "Pielāgots izmērs (px)",
        "px",
        "Lejupielādēt QR kodu",
        "Tīmekļa vietne",
        "Wi-Fi",
        "Kontaktpersona (vCard)",
        "E-pasts",
        "Tālrunis",
        "Tīkla nosaukums (SSID)",
        "Parole",
        "Slēpts tīkls",
        "Nav",
        "WPA/WPA2",
        "WEP",
        "Vārds",
        "Uzvārds",
        "Tālrunis",
        "E-pasts",
        "Uzņēmums",
        "Amata nosaukums",
        "Adrese",
        "Tīmekļa vietne",
        "E-pasta adrese",
        "Temats",
        "Ziņojums",
        "Tālruņa numurs",
    ),
    "el": row(
        "Εισαγάγετε URL ή κείμενο εδώ...",
        "Τύπος QR",
        "Ανάλυση",
        "Χρώματα",
        "Χρώμα προσκηνίου",
        "Χρώμα φόντου",
        "Εμφάνιση φόντου",
        "Ακτίνα γωνιών",
        "Προσαρμοσμένο μέγεθος (px)",
        "px",
        "Λήψη κωδικού QR",
        "Ιστότοπος",
        "Wi-Fi",
        "Επαφή (vCard)",
        "Email",
        "Τηλέφωνο",
        "Όνομα δικτύου (SSID)",
        "Κωδικός",
        "Κρυφό δίκτυο",
        "Καμία",
        "WPA/WPA2",
        "WEP",
        "Όνομα",
        "Επώνυμο",
        "Τηλέφωνο",
        "Email",
        "Εταιρεία",
        "Ιδιότητα",
        "Διεύθυνση",
        "Ιστότοπος",
        "Διεύθυνση email",
        "Θέμα",
        "Μήνυμα",
        "Αριθμός τηλεφώνου",
    ),
    "he": row(
        "הזינו כתובת או טקסט כאן...",
        "סוג QR",
        "רזולוציה",
        "צבעים",
        "צבע חזית",
        "צבע רקע",
        "הצג רקע",
        "רדיוס פינות",
        "גודל מותאם (px)",
        "px",
        "הורדת קוד QR",
        "אתר",
        "Wi-Fi",
        "איש קשר (vCard)",
        "אימייל",
        "טלפון",
        "שם הרשת (SSID)",
        "סיסמה",
        "רשת נסתרת",
        "ללא",
        "WPA/WPA2",
        "WEP",
        "שם פרטי",
        "שם משפחה",
        "טלפון",
        "אימייל",
        "חברה",
        "תפקיד",
        "כתובת",
        "אתר",
        "כתובת אימייל",
        "נושא",
        "הודעה",
        "מספר טלפון",
    ),
    "ja": row(
        "URLまたはテキストを入力...",
        "QRタイプ",
        "解像度",
        "色",
        "前景色",
        "背景色",
        "背景を表示",
        "角の丸み",
        "カスタムサイズ（px）",
        "px",
        "QRコードをダウンロード",
        "ウェブサイト",
        "Wi-Fi",
        "連絡先（vCard）",
        "メール",
        "電話",
        "ネットワーク名（SSID）",
        "パスワード",
        "非表示ネットワーク",
        "なし",
        "WPA/WPA2",
        "WEP",
        "名",
        "姓",
        "電話",
        "メール",
        "会社",
        "役職",
        "住所",
        "ウェブサイト",
        "メールアドレス",
        "件名",
        "本文",
        "電話番号",
    ),
    "ko": row(
        "URL 또는 텍스트를 입력하세요...",
        "QR 유형",
        "해상도",
        "색상",
        "전경색",
        "배경색",
        "배경 표시",
        "모서리 반경",
        "사용자 지정 크기(px)",
        "px",
        "QR 코드 다운로드",
        "웹사이트",
        "Wi-Fi",
        "연락처(vCard)",
        "이메일",
        "전화",
        "네트워크 이름(SSID)",
        "암호",
        "숨겨진 네트워크",
        "없음",
        "WPA/WPA2",
        "WEP",
        "이름",
        "성",
        "전화",
        "이메일",
        "회사",
        "직함",
        "주소",
        "웹사이트",
        "이메일 주소",
        "제목",
        "메시지",
        "전화번호",
    ),
    "zh_Hans": row(
        "在此输入网址或文本...",
        "二维码类型",
        "分辨率",
        "颜色",
        "前景色",
        "背景色",
        "显示背景",
        "圆角半径",
        "自定义大小（px）",
        "px",
        "下载二维码",
        "网站",
        "无线局域网",
        "联系人（vCard）",
        "电子邮件",
        "电话",
        "网络名称（SSID）",
        "密码",
        "隐藏网络",
        "无",
        "WPA/WPA2",
        "WEP",
        "名",
        "姓",
        "电话",
        "电子邮件",
        "公司",
        "职位",
        "地址",
        "网站",
        "电子邮箱地址",
        "主题",
        "正文",
        "电话号码",
    ),
    "zh_Hant": row(
        "在此輸入網址或文字...",
        "QR 類型",
        "解析度",
        "顏色",
        "前景顏色",
        "背景顏色",
        "顯示背景",
        "圓角半徑",
        "自訂大小（px）",
        "px",
        "下載 QR 碼",
        "網站",
        "Wi-Fi",
        "聯絡人（vCard）",
        "電子郵件",
        "電話",
        "網路名稱（SSID）",
        "密碼",
        "隱藏網路",
        "無",
        "WPA/WPA2",
        "WEP",
        "名字",
        "姓氏",
        "電話",
        "電子郵件",
        "公司",
        "職稱",
        "地址",
        "網站",
        "電子郵件地址",
        "主旨",
        "內文",
        "電話號碼",
    ),
    "id": row(
        "Masukkan URL atau teks di sini...",
        "Jenis QR",
        "Resolusi",
        "Warna",
        "Warna latar depan",
        "Warna latar belakang",
        "Tampilkan latar belakang",
        "Radius sudut",
        "Ukuran khusus (px)",
        "px",
        "Unduh kode QR",
        "Situs web",
        "Wi-Fi",
        "Kontak (vCard)",
        "Email",
        "Telepon",
        "Nama jaringan (SSID)",
        "Kata sandi",
        "Jaringan tersembunyi",
        "Tidak ada",
        "WPA/WPA2",
        "WEP",
        "Nama depan",
        "Nama belakang",
        "Telepon",
        "Email",
        "Perusahaan",
        "Jabatan",
        "Alamat",
        "Situs web",
        "Alamat email",
        "Subjek",
        "Pesan",
        "Nomor telepon",
    ),
    "vi": row(
        "Nhập URL hoặc văn bản tại đây...",
        "Loại QR",
        "Độ phân giải",
        "Màu sắc",
        "Màu nền trước",
        "Màu nền sau",
        "Hiển thị nền",
        "Bo góc",
        "Kích thước tùy chỉnh (px)",
        "px",
        "Tải mã QR",
        "Trang web",
        "Wi-Fi",
        "Danh bạ (vCard)",
        "Email",
        "Điện thoại",
        "Tên mạng (SSID)",
        "Mật khẩu",
        "Mạng ẩn",
        "Không",
        "WPA/WPA2",
        "WEP",
        "Tên",
        "Họ",
        "Điện thoại",
        "Email",
        "Công ty",
        "Chức danh",
        "Địa chỉ",
        "Trang web",
        "Địa chỉ email",
        "Tiêu đề",
        "Nội dung",
        "Số điện thoại",
    ),
    "th": row(
        "ใส่ URL หรือข้อความที่นี่...",
        "ประเภท QR",
        "ความละเอียด",
        "สี",
        "สีพื้นหน้า",
        "สีพื้นหลัง",
        "แสดงพื้นหลัง",
        "รัศมีมุม",
        "ขนาดกำหนดเอง (px)",
        "px",
        "ดาวน์โหลดคิวอาร์โค้ด",
        "เว็บไซต์",
        "Wi-Fi",
        "รายชื่อติดต่อ (vCard)",
        "อีเมล",
        "โทรศัพท์",
        "ชื่อเครือข่าย (SSID)",
        "รหัสผ่าน",
        "เครือข่ายที่ซ่อนอยู่",
        "ไม่มี",
        "WPA/WPA2",
        "WEP",
        "ชื่อ",
        "นามสกุล",
        "โทรศัพท์",
        "อีเมล",
        "บริษัท",
        "ตำแหน่ง",
        "ที่อยู่",
        "เว็บไซต์",
        "ที่อยู่อีเมล",
        "หัวเรื่อง",
        "ข้อความ",
        "หมายเลขโทรศัพท์",
    ),
    "ms": row(
        "Masukkan URL atau teks di sini...",
        "Jenis QR",
        "Resolusi",
        "Warna",
        "Warna latar hadapan",
        "Warna latar belakang",
        "Tunjukkan latar belakang",
        "Radius sudut",
        "Saiz tersuai (px)",
        "px",
        "Muat turun kod QR",
        "Laman web",
        "Wi-Fi",
        "Kenalan (vCard)",
        "E-mel",
        "Telefon",
        "Nama rangkaian (SSID)",
        "Kata laluan",
        "Rangkaian tersembunyi",
        "Tiada",
        "WPA/WPA2",
        "WEP",
        "Nama pertama",
        "Nama akhir",
        "Telefon",
        "E-mel",
        "Syarikat",
        "Jawatan",
        "Alamat",
        "Laman web",
        "Alamat e-mel",
        "Subjek",
        "Mesej",
        "Nombor telefon",
    ),
    "kk": row(
        "URL немесе мәтінді енгізіңіз...",
        "QR түрі",
        "Ажыратымдылық",
        "Түстер",
        "Алдыңғы түс",
        "Фон түсі",
        "Фонды көрсету",
        "Бұрыш радиусы",
        "Теңшелетін өлшем (px)",
        "px",
        "QR кодты жүктеу",
        "Веб-сайт",
        "Wi-Fi",
        "Контакт (vCard)",
        "Электрондық пошта",
        "Телефон",
        "Желі атауы (SSID)",
        "Құпия сөз",
        "Жасырын желі",
        "Жоқ",
        "WPA/WPA2",
        "WEP",
        "Аты",
        "Тегі",
        "Телефон",
        "Электрондық пошта",
        "Компания",
        "Лауазымы",
        "Мекенжай",
        "Веб-сайт",
        "Электрондық пошта мекенжайы",
        "Тақырып",
        "Хабарлама",
        "Телефон нөмірі",
    ),
    "az": row(
        "URL və ya mətni daxil edin...",
        "QR növü",
        "Görüntü imkanı",
        "Rənglər",
        "Ön plan rəngi",
        "Arxa fon rəngi",
        "Arxa fonu göstər",
        "Künclərin radiusu",
        "Fərdi ölçü (px)",
        "px",
        "QR kodu endir",
        "Veb sayt",
        "Wi-Fi",
        "Əlaqə (vCard)",
        "E-poçt",
        "Telefon",
        "Şəbəkə adı (SSID)",
        "Parol",
        "Gizli şəbəkə",
        "Yoxdur",
        "WPA/WPA2",
        "WEP",
        "Ad",
        "Soyad",
        "Telefon",
        "E-poçt",
        "Şirkət",
        "Vəzifə",
        "Ünvan",
        "Veb sayt",
        "E-poçt ünvanı",
        "Mövzu",
        "Mesaj",
        "Telefon nömrəsi",
    ),
    "uz": row(
        "URL yoki matnni kiriting...",
        "QR turi",
        "Piksellar",
        "Ranglar",
        "Old fon rangi",
        "Fon rangi",
        "Fonni ko‘rsatish",
        "Burchak radiusi",
        "Maxsus o‘lcham (px)",
        "px",
        "QR kodni yuklab olish",
        "Veb-sayt",
        "Wi-Fi",
        "Kontakt (vCard)",
        "Elektron pochta",
        "Telefon",
        "Tarmoq nomi (SSID)",
        "Parol",
        "Yashirin tarmoq",
        "Yo‘q",
        "WPA/WPA2",
        "WEP",
        "Ism",
        "Familiya",
        "Telefon",
        "Elektron pochta",
        "Kompaniya",
        "Lavozim",
        "Manzil",
        "Veb-sayt",
        "Elektron pochta manzili",
        "Mavzu",
        "Xabar",
        "Telefon raqami",
    ),
    "hi": row(
        "यहाँ URL या टेक्स्ट दर्ज करें...",
        "QR प्रकार",
        "रिज़ॉल्यूशन",
        "रंग",
        "अग्रभूमि रंग",
        "पृष्ठभूमि रंग",
        "पृष्ठभूमि दिखाएँ",
        "कोने की त्रिज्या",
        "कस्टम आकार (px)",
        "px",
        "QR कोड डाउनलोड करें",
        "वेबसाइट",
        "Wi-Fi",
        "संपर्क (vCard)",
        "ईमेल",
        "फ़ोन",
        "नेटवर्क नाम (SSID)",
        "पासवर्ड",
        "छुपा नेटवर्क",
        "कोई नहीं",
        "WPA/WPA2",
        "WEP",
        "पहला नाम",
        "अंतिम नाम",
        "फ़ोन",
        "ईमेल",
        "कंपनी",
        "पद",
        "पता",
        "वेबसाइट",
        "ईमेल पता",
        "विषय",
        "संदेश",
        "फ़ोन नंबर",
    ),
    "bn": row(
        "এখানে URL বা টেক্সট লিখুন...",
        "QR ধরন",
        "রেজোলিউশন",
        "রঙ",
        "পূর্বভূমির রঙ",
        "পটভূমির রঙ",
        "পটভূমি দেখান",
        "কোণের ব্যাসার্ধ",
        "কাস্টম আকার (px)",
        "px",
        "QR কোড ডাউনলোড",
        "ওয়েবসাইট",
        "Wi-Fi",
        "যোগাযোগ (vCard)",
        "ইমেইল",
        "ফোন",
        "নেটওয়ার্কের নাম (SSID)",
        "পাসওয়ার্ড",
        "লুকানো নেটওয়ার্ক",
        "কোনো নয়",
        "WPA/WPA2",
        "WEP",
        "নামের প্রথম অংশ",
        "নামের শেষাংশ",
        "ফোন",
        "ইমেইল",
        "কোম্পানি",
        "পদবি",
        "ঠিকানা",
        "ওয়েবসাইট",
        "ইমেইল ঠিকানা",
        "বিষয়",
        "বার্তা",
        "ফোন নম্বর",
    ),
    "ur": row(
        "یہاں URL یا متن درج کریں...",
        "QR کی قسم",
        "ریزولوشن",
        "رنگ",
        "پیش منظر کا رنگ",
        "پس منظر کا رنگ",
        "پس منظر دکھائیں",
        "کونے کا رداس",
        "حسب ضرورت سائز (px)",
        "px",
        "QR کوڈ ڈاؤن لوڈ",
        "ویب سائٹ",
        "Wi-Fi",
        "رابطہ (vCard)",
        "ای میل",
        "فون",
        "نیٹ ورک کا نام (SSID)",
        "پاس ورڈ",
        "پوشیدہ نیٹ ورک",
        "کوئی نہیں",
        "WPA/WPA2",
        "WEP",
        "پہلا نام",
        "آخری نام",
        "فون",
        "ای میل",
        "کمپنی",
        "عہدہ",
        "پتہ",
        "ویب سائٹ",
        "ای میل پتہ",
        "موضوع",
        "پیغام",
        "فون نمبر",
    ),
    "hy": row(
        "Մուտքագրեք URL կամ տեքստ այստեղ...",
        "QR տեսակ",
        "Բանաչափ",
        "Գույներ",
        "Առաջին պլանի գույն",
        "Ֆոնի գույն",
        "Ցուցադրել ֆոնը",
        "Անկյունների շառավիղ",
        "Պատվերով չափ (px)",
        "px",
        "Ներբեռնել QR կոդը",
        "Կայք",
        "Wi-Fi",
        "Կոնտակտ (vCard)",
        "Էլ. փոստ",
        "Հեռախոս",
        "Ցանցի անուն (SSID)",
        "Գաղտնաբառ",
        "Թաքնված ցանց",
        "Ոչ մեկը",
        "WPA/WPA2",
        "WEP",
        "Անուն",
        "Ազգանուն",
        "Հեռախոս",
        "Էլ. փոստ",
        "Ընկերություն",
        "Պաշտոն",
        "Հասցե",
        "Կայք",
        "Էլ. փոստի հասցե",
        "Թեմա",
        "Հաղորդագրություն",
        "Հեռախոսահամար",
    ),
    "ka": row(
        "შეიყვანეთ URL ან ტექსტი აქ...",
        "QR ტიპი",
        "გარჩევადობა",
        "ფერები",
        "წინა პლანის ფერი",
        "ფონის ფერი",
        "ფონის ჩვენება",
        "კუთხეების რადიუსი",
        "მორგებული ზომა (px)",
        "px",
        "QR კოდის ჩამოტვირთვა",
        "ვებსაიტი",
        "Wi-Fi",
        "კონტაქტი (vCard)",
        "ელფოსტა",
        "ტელეფონი",
        "ქსელის სახელი (SSID)",
        "პაროლი",
        "დამალული ქსელი",
        "არცერთი",
        "WPA/WPA2",
        "WEP",
        "სახელი",
        "გვარი",
        "ტელეფონი",
        "ელფოსტა",
        "კომპანია",
        "თანამდებობა",
        "მისამართი",
        "ვებსაიტი",
        "ელფოსტის მისამართი",
        "თემა",
        "შეტყობინება",
        "ტელეფონის ნომერი",
    ),
}

if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "i18n" / "qr_lang_patches.json"
    out.write_text(json.dumps(PATCHES, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(out)
